// src/services/reports/leocamReport.ts
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';
import jsPDF from 'jspdf';

/**
 * Generate both Word document and PDF reports for LEOCAM checkout results
 * 
 * @param results The LEOCAM test results
 * @returns A promise that resolves to the filename of the saved reports
 */
export async function generateLEOCAMReport(results: any): Promise<string> {
  try {
    // Generate both Word and PDF reports
    const wordFilename = await generateLEOCAMWordReport(results);
    const pdfFilename = await generateLEOCAMPDFReport(results);
    
    return `${wordFilename} and ${pdfFilename}`;
  } catch (error) {
    console.error('❌ Error generating LEOCAM reports:', error);
    throw new Error(`Failed to generate LEOCAM reports: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Generate a Word document report for LEOCAM checkout results
 * 
 * @param results The LEOCAM test results
 * @returns A promise that resolves to the filename of the saved report
 */
async function generateLEOCAMWordReport(results: any): Promise<string> {
  // Get current date and time for the report filename
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0]; // YYYY-MM-DD
  const timeStr = now.toTimeString().split(' ')[0].replace(/:/g, '-'); // HH-MM-SS
  const filename = `LEOCAM_Checkout_${dateStr}_${timeStr}.docx`;
  
  console.log(`📝 Generating LEOCAM Word report: ${filename}`);
  
  // Create the document
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        // Title
        new Paragraph({
          text: "LEOCAM Automated Self Check Out Test Report",
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 }
        }),
        
        // Test metadata
        new Paragraph({
          text: `Test Version: 24.3.21`,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: `Test Date: ${now.toLocaleDateString()}`,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: `Test Time: ${now.toLocaleTimeString()}`,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: `Generated by: SATS - Satellite Automated Testing System`,
          spacing: { after: 200 }
        }),
        
        // Test Summary
        new Paragraph({
          text: "Test Summary",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: `Tested Options: ${results.testedOptions ? results.testedOptions.join(', ') : 'Default configuration'}`,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: `Test Status: ${results.error ? 'FAILED' : 'COMPLETED'}`,
          spacing: { after: 100 }
        }),
        
        // Separator
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 200 }
        }),
        
        // Voltage Current On Summary
        new Paragraph({
          text: "* Voltage Current On Summary:",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 100 }
        }),
        
        ...createVoltageOnParagraphs(results),
        
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 200, before: 200 }
        }),
        
        // LEOCAM Configuration section
        new Paragraph({
          text: "* LEOCAM Configuration:",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 100 }
        }),
        
        ...createConfigurationParagraphs(results),
        
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 200, before: 200 }
        }),
        
        // Page break
        new Paragraph({
          text: "",
          pageBreakBefore: true
        }),
        
        // LEOCAM Telemetry section
        new Paragraph({
          text: "* LEOCAM Telemetry:",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 100 }
        }),
        
        ...createTelemetryParagraphs(results),
        
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "Statistics : -",
          spacing: { after: 100 }
        }),
        
        ...createStatisticsParagraphs(results),
        
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 200, before: 200 }
        }),
        
        // Page break
        new Paragraph({
          text: "",
          pageBreakBefore: true
        }),
        
        // Voltage Current Off Summary
        new Paragraph({
          text: "* Voltage Current Off Summary:",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 100 }
        }),
        
        ...createVoltageOffParagraphs(results),
        
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 200, before: 200 }
        }),
        
        // Test Completion Summary
        new Paragraph({
          text: "* Test Completion Summary:",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: results.error ? `Test completed with errors: ${results.error}` : "All tests completed successfully",
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: `Report generated: ${now.toLocaleString()}`,
          spacing: { after: 100 }
        }),
        new Paragraph({
          text: "--------------------------------------------------------------------",
          spacing: { after: 200, before: 200 }
        }),
      ]
    }]
  });
  
  try {
    // Generate the document
    console.log('🔄 Generating Word document...');
    const buffer = await Packer.toBuffer(doc);
    
    // Save the file using file-saver (this will save to the user's default Downloads folder)
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
    saveAs(blob, filename);
    
    console.log(`✅ LEOCAM Word report saved successfully: ${filename}`);
    
    // Mark the report as generated
    if (results && typeof results === 'object') {
      results.reportGenerated = true;
    }
    
    return filename;
  } catch (error) {
    console.error('❌ Error generating LEOCAM Word report:', error);
    throw new Error(`Failed to generate LEOCAM Word report: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Generate a PDF report for LEOCAM checkout results
 * 
 * @param results The LEOCAM test results
 * @returns A promise that resolves to the filename of the saved PDF report
 */
async function generateLEOCAMPDFReport(results: any): Promise<string> {
  // Get current date and time for the report filename
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0]; // YYYY-MM-DD
  const timeStr = now.toTimeString().split(' ')[0].replace(/:/g, '-'); // HH-MM-SS
  const filename = `LEOCAM_Checkout_${dateStr}_${timeStr}.pdf`;
  
  console.log(`📝 Generating LEOCAM PDF report: ${filename}`);
  
  try {
    // Create new PDF document
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Set up the document
    let yPosition = 20;
    const pageWidth = pdf.internal.pageSize.width;
    const pageHeight = pdf.internal.pageSize.height;
    const margin = 20;
    const contentWidth = pageWidth - (2 * margin);

    // Helper function to check if we need a new page
    const checkNewPage = (requiredSpace: number = 20) => {
      if (yPosition + requiredSpace > pageHeight - 30) {
        pdf.addPage();
        yPosition = 20;
        return true;
      }
      return false;
    };

    // Title
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('LEOCAM Automated Self Check Out Test Report', margin, yPosition);
    yPosition += 15;

    // Subtitle
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Generated by SATS - Satellite Automated Testing System', margin, yPosition);
    yPosition += 10;

    // Test metadata
    pdf.setFontSize(10);
    pdf.text(`Test Date: ${now.toLocaleDateString()}`, margin, yPosition);
    yPosition += 6;
    pdf.text(`Test Time: ${now.toLocaleTimeString()}`, margin, yPosition);
    yPosition += 6;
    pdf.text(`Tested Options: ${results.testedOptions ? results.testedOptions.join(', ') : 'Default configuration'}`, margin, yPosition);
    yPosition += 6;
    pdf.text(`Test Status: ${results.error ? 'FAILED' : 'COMPLETED'}`, margin, yPosition);
    yPosition += 15;

    // Add a separator line
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // Voltage Current On Section
    checkNewPage(40);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Voltage Current On Summary', margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (results.voltageTests) {
      const voltageData = results.voltageTests;
      
      // GPS
      if (voltageData.gps) {
        pdf.text(`GPS Voltage: ${parseFloat(voltageData.gps.voltage || "0").toFixed(3)} V [${voltageData.gps.passInitial ? 'PASS' : 'FAIL'}]`, margin, yPosition);
        yPosition += 6;
        pdf.text(`GPS Current: ${parseFloat(voltageData.gps.current || "0").toFixed(3)} A`, margin, yPosition);
        yPosition += 8;
      }
      
      // PCS
      if (voltageData.pcs) {
        pdf.text(`PCS Voltage: ${parseFloat(voltageData.pcs.voltage || "0").toFixed(3)} V [${voltageData.pcs.passInitial ? 'PASS' : 'FAIL'}]`, margin, yPosition);
        yPosition += 6;
        pdf.text(`PCS Current: ${parseFloat(voltageData.pcs.current || "0").toFixed(3)} A`, margin, yPosition);
        yPosition += 8;
      }
      
      // LEOCAM
      if (voltageData.leocam) {
        pdf.text(`LEOCAM Voltage: ${parseFloat(voltageData.leocam.voltage || "0").toFixed(3)} V [${voltageData.leocam.passInitial ? 'PASS' : 'FAIL'}]`, margin, yPosition);
        yPosition += 6;
        pdf.text(`LEOCAM Current: ${parseFloat(voltageData.leocam.current || "0").toFixed(3)} A`, margin, yPosition);
        yPosition += 8;
      }
    } else {
      pdf.text('Voltage test information not available', margin, yPosition);
      yPosition += 6;
    }
    yPosition += 10;

    // LEOCAM Configuration Section
    checkNewPage(50);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('LEOCAM Configuration', margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (results.leocamConfig) {
      const config = results.leocamConfig;
      const roiValues = config.sensorRoi || [];
      const roiStr = roiValues.length > 0 ? roiValues.join('') : 'N/A';
      
      pdf.text(`Sensor Mode: ${config.sensorMode || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor Power: ${config.sensorPower || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor Line Frame Rate: ${config.sensorLineFrameRate || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor Bit Depth: ${config.sensorBitDepth || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor ROI: ${roiStr}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor Gain Analog: ${config.sensorGainAnalog || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor Scan Direction: ${config.sensorScanDirection || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Sensor Test Pattern Select: ${config.sensorTestPatternSel || 'N/A'}`, margin, yPosition);
      yPosition += 6;
    } else {
      pdf.text('LEOCAM configuration information not available', margin, yPosition);
      yPosition += 6;
    }
    yPosition += 15;

    // LEOCAM Telemetry Section
    checkNewPage(60);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('LEOCAM Telemetry', margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (results.leocamTelemetry) {
      const telemetry = results.leocamTelemetry;
      
      pdf.text(`Health Status: ${telemetry.healthStatus || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Current Date Time: ${telemetry.dateTime || 'N/A'}`, margin, yPosition);
      yPosition += 8;
      
      // CPU Voltages
      const cpuVoltages = telemetry.cpuVoltages || [];
      for (let i = 0; i < Math.min(cpuVoltages.length, 4); i++) {
        checkNewPage(6);
        pdf.text(`CPU Voltage ${i + 1}: ${cpuVoltages[i] || 'N/A'} V`, margin, yPosition);
        yPosition += 6;
      }
      
      // CPU Temperatures
      const cpuTemperatures = telemetry.cpuTemperatures || [];
      for (let i = 0; i < Math.min(cpuTemperatures.length, 4); i++) {
        checkNewPage(6);
        pdf.text(`CPU Temperature ${i + 1}: ${cpuTemperatures[i] || 'N/A'} °C`, margin, yPosition);
        yPosition += 6;
      }
      
      // Internal Temperatures
      const internalTemperatures = telemetry.internalTemperatures || [];
      for (let i = 0; i < Math.min(internalTemperatures.length, 4); i++) {
        checkNewPage(6);
        pdf.text(`Internal Temperature ${i + 1}: ${internalTemperatures[i] || 'N/A'} °C`, margin, yPosition);
        yPosition += 6;
      }
      
      checkNewPage(6);
      pdf.text(`Sensor Voltage: ${telemetry.sensorVoltage || 'N/A'} V`, margin, yPosition);
      yPosition += 6;
      
      // Sensor Temperatures
      const sensorTemperatures = telemetry.sensorTemperatures || [];
      for (let i = 0; i < Math.min(sensorTemperatures.length, 4); i++) {
        checkNewPage(6);
        pdf.text(`Sensor Temperature ${i + 1}: ${sensorTemperatures[i] || 'N/A'} °C`, margin, yPosition);
        yPosition += 6;
      }
      
      checkNewPage(6);
      pdf.text(`Sensor Reset: ${telemetry.sensorReset || 'N/A'}`, margin, yPosition);
      yPosition += 8;
      
      // Disk data (limited to prevent overflow)
      const diskUsed = telemetry.diskUsed || [];
      for (let i = 0; i < Math.min(diskUsed.length, 2); i++) {
        checkNewPage(6);
        pdf.text(`Disk Used ${i + 1}: ${diskUsed[i] || 'N/A'} Kbytes`, margin, yPosition);
        yPosition += 6;
      }
      
    } else {
      pdf.text('LEOCAM telemetry information not available', margin, yPosition);
      yPosition += 6;
    }
    yPosition += 15;

    // Statistics Section
    checkNewPage(30);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Statistics', margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (results.leocamStatistics) {
      const stats = results.leocamStatistics;
      pdf.text(`Command Count: ${stats.commandCount || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Acknowledge Count: ${stats.acknowledgeCount || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Timeout Count: ${stats.timeoutCount || 'N/A'}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`Error Count: ${stats.errorCount || 'N/A'}`, margin, yPosition);
      yPosition += 6;
    } else {
      pdf.text('Statistics information not available', margin, yPosition);
      yPosition += 6;
    }
    yPosition += 15;

    // Voltage Current Off Section
    checkNewPage(40);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Voltage Current Off Summary', margin, yPosition);
    yPosition += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (results.voltageTests) {
      const voltageData = results.voltageTests;
      
      // GPS
      if (voltageData.gps) {
        pdf.text(`GPS Voltage: ${parseFloat(voltageData.gps.voltage || "0").toFixed(3)} V [${voltageData.gps.passFinal ? 'PASS' : 'FAIL'}]`, margin, yPosition);
        yPosition += 6;
        pdf.text(`GPS Current: ${parseFloat(voltageData.gps.current || "0").toFixed(3)} A`, margin, yPosition);
        yPosition += 8;
      }
      
      // PCS
      if (voltageData.pcs) {
        pdf.text(`PCS Voltage: ${parseFloat(voltageData.pcs.voltage || "0").toFixed(3)} V [${voltageData.pcs.passFinal ? 'PASS' : 'FAIL'}]`, margin, yPosition);
        yPosition += 6;
        pdf.text(`PCS Current: ${parseFloat(voltageData.pcs.current || "0").toFixed(3)} A`, margin, yPosition);
        yPosition += 8;
      }
      
      // LEOCAM
      if (voltageData.leocam) {
        pdf.text(`LEOCAM Voltage: ${parseFloat(voltageData.leocam.voltage || "0").toFixed(3)} V [${voltageData.leocam.passFinal ? 'PASS' : 'FAIL'}]`, margin, yPosition);
        yPosition += 6;
        pdf.text(`LEOCAM Current: ${parseFloat(voltageData.leocam.current || "0").toFixed(3)} A`, margin, yPosition);
        yPosition += 8;
      }
    } else {
      pdf.text('Final voltage test information not available', margin, yPosition);
      yPosition += 6;
    }

    // Add footer to all pages
    const totalPages = pdf.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10);
      pdf.text(`Generated: ${now.toLocaleString()}`, margin, pageHeight - 10);
    }

    // Save the PDF
    pdf.save(filename);

    console.log(`✅ LEOCAM PDF report saved successfully: ${filename}`);
    return filename;

  } catch (error) {
    console.error('❌ Error generating LEOCAM PDF report:', error);
    throw new Error(`Failed to generate LEOCAM PDF report: ${error instanceof Error ? error.message : String(error)}`);
  }
}

// Helper functions to create document paragraphs

/**
 * Create paragraphs for the Voltage On section
 */
function createVoltageOnParagraphs(results: any): Paragraph[] {
  const gpsVoltage = parseFloat(results.voltageTests?.gps?.voltage || "0").toFixed(3);
  const gpsCurrent = parseFloat(results.voltageTests?.gps?.current || "0").toFixed(3);
  const gpsStatus = results.voltageTests?.gps?.passInitial ? "[PASS]" : "[FAIL]";
  
  const pcsVoltage = parseFloat(results.voltageTests?.pcs?.voltage || "0").toFixed(3);
  const pcsCurrent = parseFloat(results.voltageTests?.pcs?.current || "0").toFixed(3);
  const pcsStatus = results.voltageTests?.pcs?.passInitial ? "[PASS]" : "[FAIL]";
  
  const leocamVoltage = parseFloat(results.voltageTests?.leocam?.voltage || "0").toFixed(3);
  const leocamCurrent = parseFloat(results.voltageTests?.leocam?.current || "0").toFixed(3);
  const leocamStatus = results.voltageTests?.leocam?.passInitial ? "[PASS]" : "[FAIL]";
  
  return [
    new Paragraph(`GPS Voltage     : ${padString(gpsVoltage, 6)} V    ${gpsStatus}`),
    new Paragraph(`GPS Current     : ${padString(gpsCurrent, 6)} A`),
    new Paragraph(``),
    new Paragraph(`PCS Voltage     : ${padString(pcsVoltage, 6)} V    ${pcsStatus}`),
    new Paragraph(`PCS Current     : ${padString(pcsCurrent, 6)} A`),
    new Paragraph(``),
    new Paragraph(`LEOCAM Voltage  : ${padString(leocamVoltage, 6)} V    ${leocamStatus}`),
    new Paragraph(`LEOCAM Current  : ${padString(leocamCurrent, 6)} A`)
  ];
}

/**
 * Create paragraphs for the Configuration section
 */
function createConfigurationParagraphs(results: any): Paragraph[] {
  const config = results.leocamConfig || {};
  const roiValues = config.sensorRoi || [];
  const roiStr = roiValues.length > 0 ? roiValues.join('') : 'N/A';
  
  return [
    new Paragraph(`Sensor Mode                 : ${config.sensorMode || 'N/A'}`),
    new Paragraph(`Sensor Power                : ${config.sensorPower || 'N/A'}`),
    new Paragraph(`Sensor Line Frame Rate      : ${config.sensorLineFrameRate || 'N/A'}`),
    new Paragraph(`Sensor Bit Depth            : ${config.sensorBitDepth || 'N/A'}`),
    new Paragraph(`Sensor ROI                  : ${roiStr}`),
    new Paragraph(`Sensor Gain Analog          : ${config.sensorGainAnalog || 'N/A'}`),
    new Paragraph(`Sensor Scan Direction       : ${config.sensorScanDirection || 'N/A'}`),
    new Paragraph(`Sensor Test Pattern Select  : ${config.sensorTestPatternSel || 'N/A'}`)
  ];
}

/**
 * Create paragraphs for the Telemetry section
 */
function createTelemetryParagraphs(results: any): Paragraph[] {
  const telemetry = results.leocamTelemetry || {};
  const paragraphs: Paragraph[] = [];
  
  // Add Health Status and DateTime
  paragraphs.push(new Paragraph(`Health Status                       : ${telemetry.healthStatus || 'N/A'}`));
  paragraphs.push(new Paragraph(`Current Date Time                   : ${telemetry.dateTime || 'N/A'}`));
  
  // Add CPU Voltages
  const cpuVoltages = telemetry.cpuVoltages || [];
  for (let i = 0; i < cpuVoltages.length; i++) {
    paragraphs.push(new Paragraph(`CPU Voltage ${i + 1}                       : ${cpuVoltages[i] || 'N/A'} V`));
  }
  
  // Add CPU Temperatures
  const cpuTemperatures = telemetry.cpuTemperatures || [];
  for (let i = 0; i < cpuTemperatures.length; i++) {
    paragraphs.push(new Paragraph(`CPU Temperature ${i + 1}                   : ${cpuTemperatures[i] || 'N/A'} deg C`));
  }
  
  // Add Internal Temperatures
  const internalTemperatures = telemetry.internalTemperatures || [];
  for (let i = 0; i < internalTemperatures.length; i++) {
    paragraphs.push(new Paragraph(`Internal Temperature ${i + 1}              : ${internalTemperatures[i] || 'N/A'} deg C`));
  }
  
  // Add sensor-specific data
  paragraphs.push(new Paragraph(`Sensor Voltage                      : ${telemetry.sensorVoltage || 'N/A'} V`));
  
  const sensorTemperatures = telemetry.sensorTemperatures || [];
  for (let i = 0; i < sensorTemperatures.length; i++) {
    paragraphs.push(new Paragraph(`Sensor Temperature ${i + 1}                : ${sensorTemperatures[i] || 'N/A'} deg C`));
  }
  
  paragraphs.push(new Paragraph(`Sensor Reset                        : ${telemetry.sensorReset || 'N/A'}`));
  
  // Add disk data
  const diskUsed = telemetry.diskUsed || [];
  for (let i = 0; i < diskUsed.length; i++) {
    paragraphs.push(new Paragraph(`Disk Used ${i + 1}                         : ${diskUsed[i] || 'N/A'} Kbytes`));
  }
  
  const diskTemperatures = telemetry.diskTemperatures || [];
  for (let i = 0; i < diskTemperatures.length; i++) {
    paragraphs.push(new Paragraph(`Disk Temperature ${i + 1}                  : ${diskTemperatures[i] || 'N/A'} deg C`));
  }
  
  const diskLifetimes = telemetry.diskLifetimes || [];
  for (let i = 0; i < diskLifetimes.length; i++) {
    paragraphs.push(new Paragraph(`Disk Lifetime ${i + 1}                     : ${diskLifetimes[i] || 'N/A'} hours`));
  }
  
  const diskErrorCorrectionCounts = telemetry.diskErrorCorrectionCounts || [];
  for (let i = 0; i < diskErrorCorrectionCounts.length; i++) {
    paragraphs.push(new Paragraph(`Disk Error Correction Count ${i + 1}       : ${diskErrorCorrectionCounts[i] || 'N/A'}`));
  }
  
  const diskErrorUncorrectableCounts = telemetry.diskErrorUncorrectableCounts || [];
  for (let i = 0; i < diskErrorUncorrectableCounts.length; i++) {
    paragraphs.push(new Paragraph(`Disk Error Uncorrectable Count ${i + 1}    : ${diskErrorUncorrectableCounts[i] || 'N/A'}`));
  }
  
  const diskTotalBytesRead = telemetry.diskTotalBytesRead || [];
  for (let i = 0; i < diskTotalBytesRead.length; i++) {
    paragraphs.push(new Paragraph(`Disk Total Bytes Read ${i + 1}             : ${diskTotalBytesRead[i] || 'N/A'} MiB`));
  }

  const diskTotalBytesWritten = telemetry.diskTotalBytesWritten || [];
  for (let i = 0; i < diskTotalBytesWritten.length; i++) {
    paragraphs.push(new Paragraph(`Disk Total Bytes Written ${i + 1}          : ${diskTotalBytesWritten[i] || 'N/A'} MiB`));
  }
  
  paragraphs.push(new Paragraph(`Disk List Datasets                  : ${telemetry.diskListDatasets || 'N/A'}`));
  paragraphs.push(new Paragraph(`Disk List Datafiles in Dataset      : ${telemetry.diskListDatafilesInDataset || 'N/A'}`));
  
  return paragraphs;
}

/**
 * Create paragraphs for the Statistics section
 */
function createStatisticsParagraphs(results: any): Paragraph[] {
  const stats = results.leocamStatistics || {};
  
  return [
    new Paragraph(`Command Count       : ${stats.commandCount || 'N/A'}`),
    new Paragraph(`Acknowledge Count   : ${stats.acknowledgeCount || 'N/A'}`),
    new Paragraph(`Timeout Count       : ${stats.timeoutCount || 'N/A'}`),
    new Paragraph(`Error Count         : ${stats.errorCount || 'N/A'}`)
  ];
}

/**
 * Create paragraphs for the Voltage Off section
 */
function createVoltageOffParagraphs(results: any): Paragraph[] {
  const gpsVoltage = parseFloat(results.voltageTests?.gps?.voltage || "0").toFixed(3);
  const gpsCurrent = parseFloat(results.voltageTests?.gps?.current || "0").toFixed(3);
  const gpsStatus = results.voltageTests?.gps?.passFinal ? "[PASS]" : "[FAIL]";
  
  const pcsVoltage = parseFloat(results.voltageTests?.pcs?.voltage || "0").toFixed(3);
  const pcsCurrent = parseFloat(results.voltageTests?.pcs?.current || "0").toFixed(3);
  const pcsStatus = results.voltageTests?.pcs?.passFinal ? "[PASS]" : "[FAIL]";
  
  const leocamVoltage = parseFloat(results.voltageTests?.leocam?.voltage || "0").toFixed(3);
  const leocamCurrent = parseFloat(results.voltageTests?.leocam?.current || "0").toFixed(3);
  const leocamStatus = results.voltageTests?.leocam?.passFinal ? "[PASS]" : "[FAIL]";
  
  return [
    new Paragraph(`GPS Voltage     : ${padString(gpsVoltage, 6)} V    ${gpsStatus}`),
    new Paragraph(`GPS Current     : ${padString(gpsCurrent, 6)} A`),
    new Paragraph(``),
    new Paragraph(`PCS Voltage     : ${padString(pcsVoltage, 6)} V    ${pcsStatus}`),
    new Paragraph(`PCS Current     : ${padString(pcsCurrent, 6)} A`),
    new Paragraph(``),
    new Paragraph(`LEOCAM Voltage  : ${padString(leocamVoltage, 6)} V    ${leocamStatus}`),
    new Paragraph(`LEOCAM Current  : ${padString(leocamCurrent, 6)} A`)
  ];
}

/**
* Utility function to pad a string to a specific length
* 
* @param value The string value to pad
* @param length The desired length
* @returns The padded string
*/
function padString(value: string, length: number): string {
  if (!value) return ''.padStart(length, ' ');
  return value.padStart(length, ' ');
}